theme: jekyll-theme-hacker
title: Marghost's Github
description: Main code repository

baseurl: marghost.github.io

author:
  name: "Marghost"
  email: "marghost@protonmail.com"
  url: "https://thegeekghost.com"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Marghost"
year : "2020"
